blog_Project/App/views.py
from random import randint

from flask import Blueprint, render_template, request, session, redirect, url_for, flash, current_app, make_response, \
    jsonify

from App.SMS import sms
from App.models import *
from App.ext import db
from flask import request
from App.forms import RegisterForm
from App.verifycode import VerifyCode

bp = Blueprint('bp', __name__)


# 登陆
@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.values.get('username')
        password = request.values.get('password')
        user1 = User.query.filter(User.username == username, User.password == password).first()
        user2 = User.query.filter(User.phone == username, User.password == password).first()
        if (user1 or user2):
            session['username'] = username
            return redirect('/index/')
        else:
            flash("用户名或者密码错误")
    return render_template("login.htm", **locals())


# 注册
@bp.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # 获取数据
            username = request.values.get('nickname')
            password = request.values.get('password')
            phone = request.values.get('phonenum')
            # 保存注册用户数据
            user = User(username=username, password=password, phone=phone)
            db.session.add(user)
            db.session.commit()
            return redirect("/")
    return render_template('regist.html', **locals())


# 文章单篇显示
@bp.route('/post/')
@bp.route("/post/<int:id>/")
def post(id=-1):
    if id < 0:
        first_art = Article.query.order_by(-Article.create_time).first()
        id = first_art.aid
    articles = db.session.query(Article, Category).filter(Article.aid == id, Article.cid == Category.cid).all()
    art_list = db.session.query(Article).filter(Article.aid == id).first()
    # 上一篇
    art_list_pre = db.session.query(Article).filter(Article.aid == (id - 1)).first()
    # 下一篇
    art_list_next = db.session.query(Article).filter(Article.aid == (id + 1)).first()
    # 最近三篇文章
    three_article = Article.query.order_by(-Article.create_time).all()[:3]
    # 所有分类
    categories = Category.query.all()
    # 分类个数
    categories_len = len(categories)
    # 标签
    tag = db.session.query(Article, Tag).filter(Article.tid == Tag.tid, Article.aid == id).first()
    tags = db.session.query(Tag).all()
    # 评论
    marks = db.session.query(Mark, User).filter(Mark.uid == User.uid).all()
    # max_mark = Mark.query().order_by(-Mark.mid).first()
    return render_template('post.html', **locals())


# 登陆后的首页
@bp.route('/index/')
def index():
    title = '时事资讯'
    articles = Article.query.all()
    category_name = Category.query.all()
    tag_name = Tag.query.all()
    return render_template('index.html', **locals())


# blog 分类显示
@bp.route('/blog/')
@bp.route('/blog/<int:cid>/')
@bp.route('/blog/<int:cid>/<int:page>/')
def bloge(cid=-1, page=1):
    if cid < 0:
        # 取默认分类的所有文章(cid=1)
        category = Category.query.first()
        cid = category.cid  # 获取第一个cid

    # 获取某一分类的所有文章
    articles = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).all()
    article_num = len(articles)

    paginate = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).paginate(
        page, 4)

    # 最近三篇文章
    three_article = Article.query.order_by(-Article.create_time).all()[:3]

    # 标签
    tags = Tag.query.all()

    # 分类
    categories = Category.query.all()

    return render_template('blog.html', **locals())


# 图片验证码
@bp.route('/ver/')
def ver():
    vc = VerifyCode()
    result = vc.generate()
    # 把验证码字符串存到session
    session['code'] = vc.code
    # 创建相应对象
    response = make_response(result)
    response.headers['Content-Type'] = "image/png"
    return response


# 短信验证
@bp.route("/phone_code/", methods=['GET', 'POST'])
def send_sms():
    phone = request.values.get("phonenum")
    if phone:
        # 产生验证码
        num = randint(1000, 9999)
        # 添加到session
        session['sms'] = str(num)
        para = "{'code':'%d'}" % num
        res = sms.send(phone, para)
        return res
    return render_template("regist.html")

blog_Project/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
      {% block metas %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="robots" content="all,follow">
      {% endblock %}
  {% block title %}
    <title>{{ title }}</title>
  {% endblock %}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">#}
  {% block stylesheet %}
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="/static/css/fontastic.css">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="/static/vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- Favicon-->
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/favicon.ico') }}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  {% endblock %}
  </head>
  <body>
{% block header %}
    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{{ url_for('bp.index') }}" class="navbar-brand">爱生活更爱明明</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="{{ url_for('bp.index') }}" class="nav-link active ">首页</a>
              </li>
              <li class="nav-item"><a href="{{ url_for('bp.bloge') }}" class="nav-link ">分类</a>
              </li>
              <li class="nav-item"><a href="{{ url_for('bp.post') }}" class="nav-link ">文章</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">联系我们</a>
              </li>
            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul>
          </div>
        </div>
      </nav>
    </header>
{% endblock %}
{% block content %}

{% endblock %}
{%  block footer %}
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Bootstrap Blog</h6>
            </div>
            <div class="contact-details">
              <p>53 Broadway, Broklyn, NY 11249</p>
              <p>Phone: (020) 123 456 789</p>
              <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
                <li> <a href="#">Pricing</a></li>
                <li> <a href="#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="#">How It Works</a></li>
                <li> <a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="/static/img/small-thumbnail-1.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="/static/img/small-thumbnail-2.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="/static/img/small-thumbnail-3.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2020. abin All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 text-right">
              小铁碗 <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">备案号</a> ###### <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">点击这里</a>

              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}
{% block javascript %}
    <!-- JavaScript files-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="/static/vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="/static/js/front.js"></script>
  {% endblock %}
  </body>
</html>

blog_Project/templates/blog.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

      <div class="row">
        <!-- Latest Posts -->

        <main class="posts-listing col-lg-8">

          <div class="container">


            <div class="row">
                {% for art in paginate.items %}
              <!-- post             -->
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ url_for('bp.post',id = art[0].aid) }}"><img src="{{ art[0].picture }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{ art[0].create_time }}</div>
                    <div class="category"><a href="#">Business</a></div>
                  </div><a href="post.html">
                    <h3 class="h4">{{ art[0].title }}</h3></a>
                  <p class="text-muted">{{ art[0].content }}</p>
                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="/static/img/001.jpg" alt="..." class="img-fluid"></div>
                      <div class="title"><span>abin</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{ art[0].create_time }}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ art[0].hits }}</div>
                  </div>
                </div>
              </div>
                {% endfor %}
                    <!-- post -->
              <div class="post col-xl-6">

            </div>


            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% for current in paginate.iter_pages() %}
                <li class="page-item"><a href="{{ url_for("bp.bloge",cid =1 , page = current) }}" class="page-link active">{{ current }}</a></li>
                {% endfor %}
              </ul>
            </nav>
          </div>

{#{% endfor %}#}




        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">最近三文</h3>
            </header>
            <div class="blog-posts">
                {% for art in three_article %}
                <a href="{{ url_for('bp.post',id = art.aid)}}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ art.picture }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ art.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>{{ art.hits }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ art.comments }}</div>
                    </div>
                  </div>
                </div></a>
                {% endfor %}
            </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">分类</h3>
            </header>
            {% for i in categories %}
            <div class="item d-flex justify-content-between"><a href="{{ url_for('bp.bloge',cid=i.cid) }}">{{ i.name }}</a><span>{{ i.num }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">
            <header>
              <h3 class="h6">标签</h3>
            </header>
            <ul class="list-inline">
                {% for i in tags %}
              <li class="list-inline-item"><a href="#" class="tag">#{{ i.name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>

{% endblock %}

blog_Project/templates/login.htm
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
      <link href="https://user.news.cn/xhw_favicon.ico" rel="shortcut icon" type="image/x-icon">
    <title>登陆</title>
    <meta http-equiv="X-UA-Compatible" content="edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/pbase.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/pcommon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/puser_login.css')}}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <div class="main">


    <style>
        .show {
            display: block;
        }

        .hide {
            display: none;
        }

        .fl {
            float: left;
        }

        .fr {
            float: right;
        }

        .clear {
            clear: both;
            height: 0;
            font-size: 0;
            overflow: hidden;
        }

        #topHeader {
            height: 32px;
            text-align: center;
            border-bottom: 1px solid #c9c9ca;
            background: #f9f7f4;
        }

        #topHeader .top {
            width: 1000px;
            margin: 0 auto;
            height: inherit;
            padding: 0;
            border: 0;
            outline: none;
            list-style: none;
            font-weight: normal;
            font-style: normal;
        }

        #topHeader a {
            float: left;
            height: 32px;
            line-height: 32px;
            color: #000;
            margin: 0 10px;
            font-size: 12px;
            cursor: pointer;
            outline: none;
            text-decoration: none;
            padding: 0;
            font-weight: normal;
            font-style: normal;
            font-family: "宋体";
        }

        .widthMain {
            margin: 0 auto;
            width: 1000px;
            padding: 10px;
        }

        .xhw-logo-font {
            font-size: 18px;
            line-height: 85px;
            color: #0272b4;
            margin-left: 15px;
            font-weight: bold;
        }

        .login-info {
            position: absolute;
            bottom: 10px;
            right: 10px;
        }

        .login-info p {
            font-size: 14px;
        }

        .xhw-bulefont {
            color: #0272b4;
        }
    </style>


<!--头部-->
    <div class="widthMain" style="border-bottom: 1px solid #0272b4; position: relative;">
        <a class="fl" href="" target="_blank"><img alt="logo" src="{{ url_for('static',filename='img/logo.jpg') }}"></a>
        <p class="fl xhw-logo-font">欢迎登陆</p>
        <div class="login-info">
            <p class="hide" id="isreg_show">已有账号，<span class="xhw-bulefont pointer goto_xhwlogin">请登录</span></p>
            <p class="hide" id="notlogin_show"><span class="xhw-bulefont pointer goto_xhwlogin">登录</span><span
                    class="xhw-bulefont">&nbsp;|&nbsp;</span><span class="xhw-bulefont pointer"
                                                                   id="goto_xhwreg">注册</span></p>
            <p class="hide" id="login_show">您好，<span class="xhw-bulefont" id="xhwlogin_name"></span></p>
        </div>
        <div class="clear"></div>
    </div>
    <!--主体正文开始-->


    <div class="login-bg">
        <div class="login-div" style="background: url('/static/img/xhw_inset.png') no-repeat -10px -10px;">
        <div class="fr login-area">
            <div class="login-way">
                <span class="login-way-active pointer">密码登录</span>
                <!-- <span class="ml80 pointer">扫码登录</span> -->
            </div>
            <div class="loginpwd-way">
                {# 登陆失败报错#}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Warning!</strong> {{ message }}
        </div>
    {% endfor %}
                <form action="{{ url_for('bp.login') }}" method="POST">
{#                账号#}
                    <div style="position: relative;">
                        <input class="logininfo mt15" id="loginname" type="text" maxlength="60" placeholder="手机号码/邮箱/用户名" name = username>
                    </div>
{#                密码#}
                    <div style="position: relative;">
                        <input class="logininfo mt15" id="password" type="password" placeholder="请输入密码" name = password>
                    </div>
{#                登陆#}
                     <input class="mt15 btn-login themebgc" id="btn-login" style="color: #FFF;" value="登录" type="submit">
{#                注册#}
                     <a href="{{ url_for('bp.register') }}"><input class="mt15 btn-login" id="btn-reg" style="color: #0071b4; background-color: #e4f3fb;" value="注册" type="button"></a>
            </form>
                <span class="fl mt15 errorinfo" id="errorinfo"></span>
                <!-- <div class="fl mt15"><input type="checkbox" value="tendays" /><span class="tenday-login">&nbsp;十天内免登陆</span></div> -->
                <span class="fr mt15 mr5 forgetpwd">忘记密码？</span>
                <div class="clear"></div>

                <div class="fr mt15 third-party-login">

                    <span class="third-party-login-span fl ml10 mr10">|</span>
                    <span class="third-party-login-span fl pointer" id="qq"><img class="fl mr5" src="/static/img/qq.png"
                                                                                 alt="QQ" title="QQ">QQ</span>


                    <span class="third-party-login-span fl ml10 mr10">|</span>
                    <span class="third-party-login-span fl pointer" id="weibo"><img class="fl mr5"
                                                                                    src="/static/img/weibo.png" alt="微博"
                                                                                    title="微博">微博</span>


                    <span class="third-party-login-span fl ml10 mr10">|</span>
                    <span class="third-party-login-span fl pointer" id="wechat"><img class="fl mr5"
                                                                                     src="/static/img/weixin.png"
                                                                                     alt="微信" title="微信">微信</span>


                </div>
            </div>
            <div class="loginscan-way hide">

            </div>
        </div>
        <div class="clear"></div>
    </div>
    <input id="servicecode" type="hidden" name="servicecode" value="">
    <input id="gourl" type="hidden" name="gourl" value="">
    <input id="extargs" type="hidden" name="extargs" value="">
</div>
</div>


<style>
    .adBottom {
        background: #FFF;
        padding: 20px 0;
    }

    .footer {
        font-size: 12px;
        font-family: "宋体";
        color: #454545;
        line-height: 22px;
        padding: 10px 0 30px 0;
        background: #FFF;
        text-align: center;
    }
</style>
<div id="bottomBody">
    <div class="adBottom domPC">
        <div class="widthMain"></div>
    </div>
    <div class="domMobile"></div>
    <div class="footer">
        <p>制作单位：千锋 nz1901 陈彬</p>
    </div>
</div>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  </body>
</html>